Resources:
  # Order DB Scheme
  TradingViewOrder:
    Type: "AWS::DynamoDB::Table"
    DeletionPolicy: Retain
    Properties:
      AttributeDefinitions:
        - AttributeName: orderId
          AttributeType: N
      KeySchema:
        - AttributeName: orderId
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      TableName: ${env:AWS_DYNAMODB_TABLE_NAME_ORDER}